# Generated by Django 6.0.5 on 2026-05-22 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scenario_text", models.TextField()),
                ("scenario_type", models.CharField(max_length=50)),
                ("profession_group", models.CharField(max_length=50)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-binary"),
                            ("prefer_not", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("profession", models.CharField(max_length=100)),
                ("profession_group", models.CharField(blank=True, max_length=50)),
                ("overall_eq_score", models.FloatField(blank=True, null=True)),
                (
                    "eq_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low EQ"),
                            ("below_average", "Below Average"),
                            ("average", "Average EQ"),
                            ("above_average", "Above Average"),
                            ("exceptional", "Exceptional EQ"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("eq_dimension", models.CharField(max_length=50)),
                ("order", models.IntegerField(default=0)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessment.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="scenario",
            name="assessment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario",
                to="assessment.userassessment",
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("self_awareness_score", models.FloatField(default=0)),
                ("self_regulation_score", models.FloatField(default=0)),
                ("empathy_score", models.FloatField(default=0)),
                ("social_skills_score", models.FloatField(default=0)),
                ("motivation_score", models.FloatField(default=0)),
                ("stress_management_score", models.FloatField(default=0)),
                ("conflict_resolution_score", models.FloatField(default=0)),
                ("adaptability_score", models.FloatField(default=0)),
                ("resilience_score", models.FloatField(default=0)),
                ("overall_eq_score", models.FloatField(default=0)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("feedback_text", models.TextField(blank=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="assessment.userassessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_answer", models.TextField()),
                ("emotion_detected", models.CharField(blank=True, max_length=20)),
                ("emotion_scores", models.JSONField(blank=True, default=dict)),
                ("sentiment_label", models.CharField(blank=True, max_length=10)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("emotional_intensity", models.FloatField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_message", models.CharField(blank=True, max_length=200)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="assessment.question",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessment.userassessment",
                    ),
                ),
            ],
        ),
    ]
